### ISSUE TITLE
Layering issue with IITC-CE

### ISSUE THREAD

**Issue by fortepc** [Wintervorst/iitc#1]
I'm unsure if this is an issue with this plugin, or if it's an issue with IITC-CE, but when using this plugin the cells it draws are layered on top of portals, making then unclickable. 

https://github.com/IITC-CE/ingress-intel-total-conversion/ is the repo for the CE version of IITC where development has picked back up since the iitc.me version stopped being developed on.

**Comment by Wintervorst** [comment]
All the layer plugins use non-clickable layers, so I'd guess it has someting to do with IITC-CE.
Do you know which one of my plugins is causing you a problem. Could you disable and enable them to find out?

**Comment by johnd0e** [comment]
It's about Leaflet v1: https://github.com/IITC-CE/ingress-intel-total-conversion/issues/132#issuecomment-470954631

In order to support both Leaflet versions you can add also `interactive: false` property to unclickable layers.

**Comment by Wintervorst** [comment]
Added interactive: false to all layers of the gympossible, 17cell and 19cell plugins for support for newer leaflet library in IITC-CE.
Will you update me on the results of this update @fortepc?

**Comment by fortepc** [comment]
@Wintervorst sure, I update and report the results as soon as I get back to my desk.

**Comment by fortepc** [comment]
@Wintervorst doesn't seem to change anything, should I update the https://github.com/Wintervorst/iitc/blob/master/plugins/s2celldrawer/s2celldrawer.user.js too?

Edit1 : looks like I didn't get everything updated, one second. 

edit2: after getting everything updated it works fine! Yay :D

**Comment by jwadamson** [comment]
IITC plugin: Portal submitrange, line 75 is missing `interactive: false` option

thanks.
