### ISSUE TITLE
totalrecon doesn't work on IITCm

### ISSUE THREAD

**Issue by fortepc** [Wintervorst/iitc#2]
I've tried to set it up on my phone with IITCm, both the iitc.me fork, and the iitc-ce fork. It doesn't seem to work at all.

**Comment by Wintervorst** [comment]
Did you get the dialog [](https://raw.githubusercontent.com/Wintervorst/iitc/master/plugins/totalrecon/assets/enterscripturl.png) in IITCm and did you enable the plugin under 'Highlighters'?

![enterscripturl](https://user-images.githubusercontent.com/4071836/54018019-f054f200-4187-11e9-9907-2049fd7e4c61.png)

**Comment by fortepc** [comment]
When I install it, it shows up under "User Plugins" > "Misc" > "unknown", when I enable it nothing happens at all. I've gotten it set up and working on my desktop browser, chrome with tampermonkey and the iitc-ce.

**Comment by fortepc** [comment]
I'm installing it by clicking on this link and opening the link with the iitc app. https://github.com/Wintervorst/iitc/blob/master/plugins/totalrecon/totalrecon.user.js

**Comment by fortepc** [comment]
I'm unsure if my Android version would matter, but I am using a Google pixel XL on Android P.

**Comment by Wintervorst** [comment]
I've heard about this multiple times for different plugins, not all my own, so I don't think it's a problem with my plugins, but rather with IITC mobile.
Sometimes the solution was to remove the plugin and reinstall it. Sometimes a reboot of the device helped and sometimes it was a matter of reinstalling IITC mobile.
Hopefully one of these options solves your problem.

**Comment by fortepc** [comment]
So you're able to confirm on your end that it does work on mobile? Because I've already tried to uninstall and reinstall it a couple times, rebooting a couple times, even totally uninstalling and reinstalling the iitc apps. I am now seeing that I am also having this issue on other plug-ins as well though, so I'm leaning towards assuming that it is a issue with the IITC app, but you confirming whether or not it works for you would be helpful.

**Comment by johnd0e** [comment]
> I'm installing it by clicking on this link and opening the link with the iitc app.

Try https://github.com/Wintervorst/iitc/raw/master/plugins/totalrecon/totalrecon.user.js

**Comment by Wintervorst** [comment]
I can confirm that it does work on mobile. Several agents have got it running. Attached a screenshot from my Android device.
![photo5789921588286697404](https://user-images.githubusercontent.com/4071836/54425234-1c86ea80-4715-11e9-9b2b-1e30ed5f7ab9.jpg)

**Comment by fortepc** [comment]
Okay, it's likely something wrong with my phone specifically then, as I'm realizing no external plugins are working.

**Comment by fortepc** [comment]
I figured out the issue was with the stock Android file picker. After using ES file explorer to add the plug-in the file way it works fine on the ii-tc me fork. It still doesn't work on the community edition fork

**Comment by johnd0e** [comment]
If you have both editions of iitc installed then it's enough to install it in either of them.
After installation this plugin is available in 'USER PLUGINS / Highlighter' category.

Check if you have USER PLUGINS section in iitc-ce. If not then check if you have Storage permission granted for app.

**Comment by johnd0e** [comment]
@fortepc
Could you check filepicker in latest test build?

**Comment by Wintervorst** [comment]
> 
> 
> @fortepc
> Could you check filepicker in latest test build?

Try this intent://github.com/Wintervorst/iitc/raw/master/plugins/totalrecon/totalrecon.user.js#Intent;scheme=https;action=android.intent.action.VIEW;end;
Didn't get it working on github yet. In regular HTML page it displays properly as a link.
