### ISSUE TITLE
Latest Version of IITC-CE Broke TotalRecon

### ISSUE THREAD

**Issue by fortepc** [Wintervorst/iitc#3]
Inside the UI of IITC Nothing happened when I tried to load totalrecon today, so I tried to use the clear script and it did come up and let me re-do the script url, but still after that nothing happened, so I did a little more digging in the browser's console. 

On Click this happens: 
![image](https://user-images.githubusercontent.com/26149601/55015200-c6daf980-4fc2-11e9-8ae8-5fac192d0df8.png)

On Refresh where there should be TotalRecon tiles this happens: 
![image](https://user-images.githubusercontent.com/26149601/55015264-ea05a900-4fc2-11e9-9605-1bf21565c451.png)

If I click any of the debugger links this is what I see:
![image](https://user-images.githubusercontent.com/26149601/55015588-8039cf00-4fc3-11e9-8712-a34bbf57990c.png)

I disabled the IITC-CE and re-installed the IITC.me branch and it worked fine, I'm not sure what they changed but wanted to make sure you're aware of it. I'll switch to the IITC.me fork in the meantime when I need to use TotalRecon, thanks again for this plugin, it's awesome!

**Comment by fortepc** [comment]
I see they just made some new changes, not sure what may have caused this though. https://github.com/IITC-CE/ingress-intel-total-conversion/commits/master

**Comment by jwadamson** [comment]
commit 67f4dfab18d3231a0c33cc5e52d3f1e4858d6fd1 of IITC-CE removed window.createGenericMarker function.

I can't really trace the few commits touching that file to figure out what equivalent call would be.

**Comment by jwadamson** [comment]
window.plugin.totalrecon.createGenericMarker = function(latLng, color, opts) {
opts.color = color;
return L.marker(latLng, opts);
};

/* update the two other references tocreateGenericMarker to this absolute reference */

handling of "color" is almost certainly incorrect, but that gets some sort of marker to show up and seems to make the plugin semi-functional.

**Comment by Wintervorst** [comment]
Copied the original implementation from IITC to master version of totalrecon. Could you check if this 'fix' works on IITC-CE?
If so, I might update my other plugins with the same solution to make them compatible with IITC-CE again.

**Comment by Wintervorst** [comment]
Closed this issue. Works on the latest desktop version 0.29.1.20190518.145617.
I'll update my other plugins with this change somewhere during the next week.

**Comment by jwadamson** [comment]
working great for me now, looking good, thanks!!
