### ISSUE TITLE
Unable to "Send" or add new poi in Total Recon

### ISSUE THREAD

**Issue by fortepc** [Wintervorst/iitc#5]
Try to get a buddy of mine set up on this and he's able to see all of the map pins that I've made, but he's unable to send one himself. I had him send me a screenshot of his Dev console and this is what he saw right after trying to submit something.

![](https://i.imgur.com/IhSexEi.png)

This was on a work machine, so I'm guessing it's most likely just an over-aggressive security policy. I've set a few people up on this and it's been working great, he's the first person who I've seen have this issue. But I wanted to report it anyway, just in case it was something you'd want to know about.

**Comment by jwadamson** [comment]
window.plugin.totalrecon.createGenericMarker = function(latLng, color, opts) {
    opts.color = color;
    return L.marker(latLng, opts);
  };

/* update the two other references to`createGenericMarker` to this absolute reference */

handling of "color" is almost certainly incorrect, but that gets some sort of marker to show up and seems to make the plugin semi-functional.

**Comment by Wintervorst** [comment]
Only have seen this issue when the Google App Script did not have full permissions, but then, it shouldn't work for any user....

**Comment by Wintervorst** [comment]
Closed this issue due to the incidental nature. Do not see the need (right now) to further investigate it.
