### ISSUE TITLE
Total Recon: Should I submit patches here or create my own fork?

### ISSUE THREAD

**Issue by AlfonsoML** [Wintervorst/iitc#6]
I've been told to take a look at this plugin and I really enjoy the concept and the way that it works.  
I had some little issues in order to make it work, and I would simplify it because I don't see right now the need to keep track of the photos, sent date, or any portal that has been approved.

I would prefer if everybody could use a single version and that it would be this one, but if the type of changes that I'm proposing would not be accepted here then it's simpler for me to do all the work on my own version without any worries about compatibility and providing many pull requests.

Congratulations on the nice work!

**Comment by Wintervorst** [comment]
I'd suggest you create your own fork, since I don't see me using your modifications (in this case).
I like to keep track of things, when did I submit and when is the response received?
