### ISSUE TITLE
IITC script doesn't work since Ingress URL have changed

### ISSUE THREAD

**Issue by jrrevy** [Wintervorst/iitc#7]
Hello, 
Since ingress URL is now https://intel.ingress.com/ and no longer https://*.ingress.com/intel, I had to add 2 lines in script to match IT : 

// @match          https://intel.ingress.com/*
// @match          http://intel.ingress.com/*

May I submit a PR to change it for every one ?

**Comment by Wintervorst** [comment]
Gladly!
